USE AdventureWorks2019
GO

/*
    CAST(VALOR[NOME_DA_COLUNA] AS [TIPO_DO_DAD0])
    CONVERT([TIPO_DO_DADO], NOME_DA_COLUNA[STYLE]) 

*/

--SELECT (SELECT CAST('30' AS INT)) + (SELECT CAST('35' AS INT)) AS RESULT  #(CAST(VALOR(NOME DA COLUNA) AS TIPO DO DADO) CAST FEZ CONVERSÃO DO VALOR STRING PARA INT

--SELECT CAST('20010101' AS date)                                           #CAST CONVERTEU STRING EM DATA

--SELECT GETDATE()                                                          #RETORNA DATA E HOTA ATUAL

SELECT CONVERT(VARCHAR(10), GETDATE(),103)                                --#RETORNA DATA PARA PADRÃO BRASILEIRO

